import ProjectCard from "../../components/Cards/ProjectCards";
import tastyBytes from "../../Assets/Projects/tasty-bytes.png";
import weatherDash from "../../Assets/Projects/weather-dashboard.png";
import budgetTracker from "../../Assets/Projects/budget-tracker.png";
import agservices from "../../Assets/Projects/agservices.png";
import WireMachine from "../../Assets/Projects/WireMachine.PNG";
import PurchasingDashboard from "../../Assets/Projects/PurchasingDashboard.PNG";
import ActivityTracker from "../../Assets/Projects/ActivityTracker.PNG";
import MterialHandler from "../../Assets/Projects/MaterialHandler.png";
import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import "./Projects.css";

function Projects() {
  return (
    <Container fluid className="project-section-container">
      <Row>
        <h1 className="d-flex project-section-h1">
          Software<strong className="blue mx-1">Work </strong>
        </h1>
        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={tastyBytes}
            title="Tasty Bytes"
            description="A responsive, mobile-first, progressive web app (PWA) using HTML/CSS and JavaScript. Using the open-source Bulma CSS framework for styling. The data in this project is coming from 2 APIs Spoonacular and The Cocktail DB."
            displayBtn={true}
            link="https://julioplaceres.github.io/TastyBytes/"
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={agservices}
            title="AG Organazing And Cleaning Services"
            description="Family owned and operated, AG Organizing and Cleaning Services was founded in 2022 with the mission of providing excellent cleaning services in the Syracuse, New York area."
            displayBtn={true}
            link="https://www.agocservices.com/home"
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={weatherDash}
            title="Weather Dashboard"
            description="Application to display the weather status in different cities, allows the search history to be saved and will provide the user with a 5 days forecast."
            displayBtn={true}
            link="https://julioplaceres.github.io/Weather_App/"
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={budgetTracker}
            title="Budget Tracker"
            description="A budget Tracker application to allow for offline access and functionality. When entering transactions offline, they will populate the total when brought back online."
            displayBtn={true}
            link="https://still-bayou-73273.herokuapp.com/"
          />
        </Col>
      </Row>
      {/* Manufacturing Section */}
      <Row>
        <h1 className="d-flex project-section-h1">
          Manufacturing<strong className="blue mx-1">Work </strong>
        </h1>
        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={WireMachine}
            title="Wire Machine Dashboard"
            description="A Dashboard that tracked Defects Per Million Opportunities (DPMO) for the process 
            of creating wires that were used in the PCB auto-insertion machines. Also tracking the values of
            the First Piece Articles (FPI) generated by the operator. Not only the dashboard was used as a physical
            indicator of the process, but the data collected was also used in multiple Lean Six Sigma projects."
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={PurchasingDashboard}
            title="Purchasing Dashboard"
            description="A Dashboard that presented the latest pricing for precious minerals to aid purchasing agents in their activities.
            This dashboard was created using LabVIEW and ran a web scraping application that would retrieve the data from different trusted
            sources and would update the layout when there was a change."
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={ActivityTracker}
            title="Atcivity Tracker"
            description="Application which tracked KPIs for multiple departments and generated reports to upper managment of tasks performed 
            by each department of the organization."
          />
        </Col>

        <Col sm={6} xl={3} className="project-section-col">
          <ProjectCard
            imgPath={MterialHandler}
            title="Material Handling App"
            description="Application to aid the flow of the materials through the company by aiding supervisors to add requests and material handlers
            to processed it. Smart Reports, login/logout functionability and audit trail features were included as well."
          />
        </Col>
      </Row>
    </Container>
  );
}

export default Projects;
